include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - invalid_annotation_target: false
    - test/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
