name: template
description: Template project

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Tools
  flutter_svg: ^1.1.3
  collection: ^1.16.0
  modal_bottom_sheet: ^2.1.0
  diacritic: ^0.1.3
  flutter_native_splash: ^2.2.8
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2

  # REST API
  dio: ^4.0.6
  http: ^0.13.4
  json_serializable: ^6.2.0
  internet_connection_checker: ^0.0.1+4
  pretty_dio_logger: ^1.2.0-beta-1

  # Routing
  go_router: ^5.0.1

  # Mobile scanner
  scan: ^1.6.0

  # Logger
  loggy: ^2.0.1+1
  flutter_loggy_dio: ^2.0.0+3

  # Freezed
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

  # Riverpod
  flutter_riverpod: ^2.0.0-dev.9

  # Storage
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # Localization
  intl: ^0.17.0
  flutter_sheet_localization:
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  http: ^0.13.0
  json_serializable: ^6.1.6
  analyzer:

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  flutter_gen_runner: 4.3.0

  flutter_lints: ^2.0.1

  flutter_sheet_localization_generator:

  # tests
  integration_test:
    sdk: flutter

  mocktail: ^0.3.0
  http_mock_adapter: ^0.3.3
  hive_test: ^1.0.1

  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_native_splash:
  background_image: assets/splash/splash.png
  ios_content_mode: scaleAspectFit
  web: false
